all: my_echo task1a task1b task1c task2

my_echo: my_echo.c
	gcc -g -m32 -Wall -o my_echo my_echo.c

task1a: task1a.c
	gcc -g -m32 -Wall -o char2ascii task1a.c

task1b: task1b.c
	gcc -g -m32 -Wall -o char2ascii task1b.c

task1c: task1c.c
	gcc -g -m32 -Wall -o char2ascii task1c.c

task2: task2.c
	gcc -g -m32 -Wall -o char2ascii task2.c



