bubblesort: bubblesort.c
	gcc -g -m32 -Wall -o bubblesort bubblesort.c
hexaPrint: hexaPrint.c
	gcc -g -m32 -Wall -o hexaPrint hexaPrint.c
task1a: task1a.c
	gcc -g -m32 -Wall -o task1a task1a.c
task1b: task1b.c
	gcc -g -m32 -Wall -o task1b task1b.c
