bubblesort: bubblesort.c
	gcc -g -m32 -Wall -o bubblesort bubblesort.c
hexaPrint: hexaPrint.c
	gcc -g -m32 -Wall -o hexaPrint hexaPrint.c
task1a: task1a.c
	gcc -g -m32 -Wall -o bcmp task1a.c
task1b: task1b.c
	gcc -g -m32 -Wall -o bcmp task1b.c
task1c: task1c.c
	gcc -g -m32 -Wall -o bcmp task1c.c
task2: task2.c
	gcc -g -m32 -Wall -o bcmp task2.c
